#:schema https://mod.cloudflare.com/schemas/wrangler/config-schema.json
name = "nuvo-proxy"
main = "worker.js"
compatibility_date = "2024-03-06"

[observability]
enabled = true

[browser]
enabled = false
